version: '3'
services:
  redis:
    image: docker.io/library/redis:5.0.8
    container_name: redis-slave
    ports:
      - "6380:6380"
    volumes:
      - "./redis.conf:/usr/local/etc/redis/redis.conf"
      - "./data:/data"
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
